name: Airport-Checkin

on:
  schedule:
  - cron: 0 16 * * *
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          pip3 install -r ./requirements.txt
      - name: Run checkin
        run: |
          python3 ./main.py --token_string "${{ secrets.TOKEN }}"
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          BASE_URL: ${{ secrets.BASE_URL }}
          SCKEY: ${{ secrets.SCKEY }}
          TGBOT: ${{ secrets.TGBOT }}
          TGUSERID: ${{ secrets.TGUSERID }}
      - uses: gautamkrishnar/keepalive-workflow@master
